### ISSUE TITLE
Improve the feature weights figure to be continous within a region

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/AEC-wPLI-comparison#12]
## Todo:
- [x] Rebuild the API for the plotting to be more understandable, right now its a mess to work with
- [x] Generate figure with dummy data for one color for one continuous weight vector
- [x] Modify the code to generate two basic color for two different weight vector
- [x] Get the weights vector from the result for the func connectivity for aec
- [x] Get the weights vector from the result for the func connecvtity for wpli
- [x] Make a pipe to take the weights of both mean and std, normalize them together and separate them.
- [x] Make a script to load the weights use the pipe and generate two different plot one for mean and one for std

## Documentation
For this comment from Reviewer 1:
"These thresholded plots of Figure 4D  are fine for visualization, but they are not ideal for drawing conclusions from the data. A quantitative analysis comparing brain distributions of features based on the entire dataset, not just the top 20%, would be more compelling."
We can very easily use a gradient of color and sum them up for all the feature weights. It would go from pale to dark on each of the same color and we can put all of this on the same brain:
yellow for mean
blue for std
We can then mix the pure yellow and pure blue together for each regions and that will give use a semi-continous coloration of the participation of the mean and std to a particular region. I say semi-continous because the boundary between the regions will be hard boundary.
Since we already have the code for the figure this shouldn't take me more than 2h to setup. Once again the longest part would be to make the actual paper grade figure.

**Comment by yacineMahdid** [comment]
Scaling the colour by applying the weights as a transparency is horrendous, will go with a colormap instead with solid colors.
