### ISSUE TITLE
Generate the wPLI matrices with a 0.1 sliding window

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/AEC-wPLI-comparison#15]
This is straightforward to do since the code is already working well for wPLI.
This part should be highly parallelized and should run on the cluster with 40+ cores.
It should save the data into the server directly so that it can be used by another process. 

## TODO
- [x] Fix the script to use our wPLI with surrogates
- [x] create the script to generate the wPLI matrices from the source localized data and save the data for each participant
- [x] create the slurm file to batch the job with multiple cores
