### ISSUE TITLE
Fix the AEC code in NeuroAlgo to work like the wPLI code

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/AEC-wPLI-comparison#16]
We need that part in order to use sliding windows instead of jumpy ones.

## TODO
- [x] Modify the code to work with time steps instead of % overlap, take a look at NA.
- [x] Parallelize the code to work with as many core as available
- [x] Save the resulting aecp matrix along with the LABELS so that we can know what is what.
- [x] Iterate over each participant data and calculate the aecp from a source folder with the same structure

**Comment by yacineMahdid** [comment]
The code is very difficult to work with, I have a few thing I need to fix before I can make this flexible enough. See the **TODO**
