### ISSUE TITLE
Make connectivity figure on best participant

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/AEC-wPLI-comparison#19]
We will redo the three main connectivity figure for the participant that has the highest classification accuracy and we will add that to the supplemental figure

## TODO
- [ ] Find the best participant (wait until the machine learning section is well polished)
- [ ] Generate the matrix connectivity at each state for this participant
- [ ] Generate the mean global connectivity at each state for that participant
- [ ] Generate the std global connectivity at each state for that participant

Once the figure are generated I will stitch them all up in BioRender.
