### ISSUE TITLE
Generate the confusion matrix for the machine learning part

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/AEC-wPLI-comparison#22]
This way we can confidently show how our classifier behave. Once again I'll stitch the figure up using BioRender.

## TODO
- [ ] Generate the feature matrix using the higher resolution
- [x] Make sure that the confusion matrices are being saved
- [ ] Generate the code to make the raw plot based on the saved confusion matrices
- [ ] Make a figure in BioRender to generate the final figure based on the raw plots
